export enum COFFE_TYPES {
  IRLANDES = 'irlandes',
  ARABE = 'arabe',
  HAVAIANO = 'havaiano',
  CUBANO = 'cubano',
  MOCHACCINO = 'mochaccino',
  MACCHIATO = 'macchiato',
  CAPUCCINO = 'capuccino',
  LATTE = 'latte',
  CAFE_COM_LEITE = 'cafecomleite',
  CAFE_GELADO = 'cafegelado',
  EXPRESSO_CREMOSO = 'expressocremoso',
  AMERICANO = 'americano',
  EXPRESSO = 'expresso',
  CHOCOLATE_QUENTE = 'chocolatequente',
}
